# Generated by Django 2.0 on 2017-12-11 10:24

from django.db import migrations, models
import entry.models.entry_user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('kanji_first_name', models.CharField(max_length=20)),
                ('kanji_last_name', models.CharField(max_length=20)),
                ('kana_first_name', models.CharField(max_length=20)),
                ('kana_last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('day_of_birth', models.CharField(max_length=2)),
                ('month_of_birth', models.CharField(max_length=2)),
                ('year_of_birth', models.CharField(max_length=4)),
                ('date_of_birth', models.DateField(null=True)),
                ('post_code', models.CharField(max_length=20)),
                ('kanji_address', models.CharField(max_length=100)),
                ('kana_address', models.CharField(max_length=100)),
                ('kanji_address_other', models.CharField(max_length=100)),
                ('kana_address_other', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('tel_2', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', entry.models.entry_user.EntryUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('name', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=20)),
                ('kanji_address', models.CharField(max_length=100)),
                ('kana_address', models.CharField(max_length=100)),
                ('kanji_address_other', models.CharField(max_length=100)),
                ('kana_address_other', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('tel_2', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji_name_first', models.CharField(max_length=20)),
                ('kanji_name_last', models.CharField(max_length=20)),
                ('kana_name_first', models.CharField(max_length=20)),
                ('kana_name_last', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=20)),
                ('kanji_address', models.CharField(max_length=100)),
                ('kana_address', models.CharField(max_length=100)),
                ('kanji_address_other', models.CharField(max_length=100)),
                ('kana_address_other', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
