# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji_name_first', models.CharField(max_length=20)),
                ('kanji_name_last', models.CharField(max_length=20)),
                ('kana_name_first', models.CharField(max_length=20)),
                ('kana_name_last', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=20)),
                ('kanji_address', models.CharField(max_length=100)),
                ('kana_address', models.CharField(max_length=100)),
                ('kanji_address_other', models.CharField(max_length=100)),
                ('kana_address_other', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
